name: Continuous Integration

on:
  pull_request:
    branches:
    - develop
    - main
  push:
    branches:
    - implement-ci-cd

jobs:
  test:
    name: Tests
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Check Token
      run: |
        echo "Token: ${{ secrets.TOKEN }}"
    - name: Create .npmrc file for private NPM packages
      run: |
        echo "//npm.pkg.github.com/:_authToken=${{ secrets.TOKEN }}" > ~/.npmrc
        echo "@passiolife:registry=https://npm.pkg.github.com" >> ~/.npmrc

    - uses: actions/setup-node@master
    - uses: c-hive/gha-yarn-cache@v1

    - name: Install node modules
      run: |
        yarn install

    - name: Run linter
      run: |
        yarn lint

    - name: Run tests
      run: |
        yarn test
